import Head from 'next/head';
import { useUser } from '@auth0/nextjs-auth0';

export default function Home() {
  const { user, error, isLoading } = useUser();

  console.log('user', user);

  if (isLoading) return <div>Loading...</div>;
  if (error) return <div>{error.message}</div>;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex w-full max-w-lg mx-auto items-center justify-center">
        <h1 className="text-2xl text-gray-700">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
          <a
            href="/api/auth/login"
            className="flex text-center bg-green-700 py-4 px-6 text-white"
          >
            Login In
          </a>
          <a
            href="/api/auth/logout"
            className="flex text-center bg-green-700 py-4 px-6 text-white"
          >
            Login Out
          </a>
        </h1>
      </main>
    </>
  );
}
